# Generated by Django 5.2.13 on 2026-04-22 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(default='Con Hilo Depilo', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='brand_color',
            field=models.CharField(default='oklch(0.68 0.28 296)', max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color or OKLCH format (e.g., oklch(0.68 0.28 296))', regex='^(#[0-9a-fA-F]{6}|oklch\\([\\d.]+%? [\\d.]+ [\\d.]+\\))$')]),
        ),
    ]
