# Generated by Django 5.2.13 on 2026-04-23 01:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_companyprofile_name_alter_companyprofile_brand_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyweekdayslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='companyavailability',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='booking.companyprofile'),
        ),
        migrations.AddField(
            model_name='companydateoverride',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='booking.companyprofile'),
        ),
        migrations.AddField(
            model_name='companyweekdayslot',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weekday_slots', to='booking.companyprofile'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='brand_color',
            field=models.CharField(default='#ee5837', max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color or OKLCH format (e.g., oklch(0.68 0.28 296))', regex='^(#[0-9a-fA-F]{6}|oklch\\([\\d.]+%? [\\d.]+ [\\d.]+\\))$')]),
        ),
        migrations.AlterUniqueTogether(
            name='companyweekdayslot',
            unique_together={('company', 'weekday', 'start_time', 'end_time')},
        ),
    ]
