# Generated by Django 5.2.13 on 2026-04-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_eventtypegroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='booking_cooldown_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Booking cooldown (minutes)'),
        ),
    ]
