# Generated by Django 5.2.13 on 2026-05-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_google_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='terms_and_conditions_url',
            field=models.URLField(blank=True, null=True, verbose_name='Terms and conditions URL'),
        ),
    ]
