# Generated by Django 5.2.13 on 2026-05-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True, verbose_name='TikTok URL'),
        ),
    ]
