# Generated by Django 5.2.13 on 2026-06-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_companyprofile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
    ]
