# Generated by Django 5.2.15 on 2026-06-06 13:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models, connection


def migrate_existing_m2m_data(apps, schema_editor):
    """Migrate existing M2M data from auto-generated through table to BookingServiceThrough."""
    BookingServiceThrough = apps.get_model("booking", "BookingServiceThrough")
    Booking = apps.get_model("booking", "Booking")
    Event = apps.get_model("booking", "Event")

    # Determine the correct table names dynamically
    through_table = BookingServiceThrough._meta.db_table  # booking_bookingservicethrough

    with connection.cursor() as cursor:
        try:
            cursor.execute("""
                SELECT COUNT(*) FROM booking_booking_services
            """)
            count = cursor.fetchone()[0]
            if count == 0:
                return
        except Exception:
            return

        # Copy existing M2M rows to new through model with quantity=1 and unit_price=Event.price
        cursor.execute(f"""
            INSERT INTO {through_table} (booking_id, event_id, quantity, unit_price)
            SELECT
                bst.booking_id,
                bst.event_id,
                1 as quantity,
                e.price as unit_price
            FROM booking_booking_services bst
            JOIN booking_event e ON bst.event_id = e.id
        """)

        # Backfill original_amount and total_amount on existing bookings
        cursor.execute(f"""
            UPDATE booking_booking
            SET original_amount = sub.total_original,
                discount_amount = 0.00,
                total_amount = sub.total_original
            FROM (
                SELECT
                    bst.booking_id,
                    SUM(bst.quantity * bst.unit_price) as total_original
                FROM {through_table} bst
                GROUP BY bst.booking_id
            ) sub
            WHERE booking_booking.id = sub.booking_id
        """)

    # Update state: ensure through model rows exist in Django state too
    for booking in Booking.objects.all():
        through_manager = BookingServiceThrough.objects.filter(booking=booking)
        if not through_manager.exists():
            for event in booking.services.all():
                BookingServiceThrough.objects.create(
                    booking=booking,
                    event=event,
                    quantity=1,
                    unit_price=event.price
                )


def drop_old_through_table(apps, schema_editor):
    """Drop the old auto-generated through table."""
    with connection.cursor() as cursor:
        try:
            cursor.execute("DROP TABLE IF EXISTS booking_booking_services CASCADE")
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0015_companyprofile_facebook_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Discount amount",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="original_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Original amount",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Total amount",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="buy_x",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Buy X items to trigger promotion. Set to 0 to disable.",
                verbose_name="Buy X",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="get_y_free",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Free items per threshold. Set to 0 to disable.",
                verbose_name="Get Y Free",
            ),
        ),
        migrations.CreateModel(
            name="BookingServiceThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantity"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Unit price"
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_services",
                        to="booking.booking",
                        verbose_name="Booking",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_services",
                        to="booking.event",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Service",
                "verbose_name_plural": "Booking Services",
                "unique_together": {("booking", "event")},
            },
        ),
        migrations.RunPython(migrate_existing_m2m_data, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="booking",
                    name="services",
                    field=models.ManyToManyField(
                        related_name="bookings",
                        through="booking.BookingServiceThrough",
                        to="booking.event",
                        verbose_name="Services",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(drop_old_through_table, migrations.RunPython.noop),
            ],
        ),
    ]