# Generated by Django 5.2.13 on 2026-06-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_add_bogo_promotion_through_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='buy_x',
        ),
        migrations.RemoveField(
            model_name='event',
            name='get_y_free',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='buy_x',
            field=models.PositiveIntegerField(default=0, help_text='Buy X items to trigger promotion. Set to 0 to disable.', verbose_name='Buy X'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='get_y_free',
            field=models.PositiveIntegerField(default=0, help_text='Free items per threshold. Set to 0 to disable.', verbose_name='Get Y Free'),
        ),
    ]
