# Generated by Django 5.2.15 on 2026-06-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_add_bogo_to_companyprofile_remove_from_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Buyer email'),
        ),
        migrations.AddField(
            model_name='booking',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyer name'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_gift',
            field=models.BooleanField(default=False, verbose_name='Is gift'),
        ),
        migrations.AddField(
            model_name='booking',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Recipient email'),
        ),
        migrations.AddField(
            model_name='booking',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Recipient name'),
        ),
    ]
