# Generated by Django 5.2.13 on 2026-04-23 18:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_companyweekdayslot_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={'verbose_name': 'Service Weekday Slot', 'verbose_name_plural': 'Service Weekday Slots'},
        ),
        migrations.AlterModelOptions(
            name='companyavailability',
            options={'verbose_name': 'Company Availability', 'verbose_name_plural': 'Company Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='companydateoverride',
            options={'verbose_name': 'Company Date Override', 'verbose_name_plural': 'Company Date Overrides'},
        ),
        migrations.AlterModelOptions(
            name='companyweekdayslot',
            options={'verbose_name': 'Company Weekday Slot', 'verbose_name_plural': 'Company Weekday Slots'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='eventavailability',
            options={'verbose_name': 'Service Availability', 'verbose_name_plural': 'Service Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='eventdateoverride',
            options={'verbose_name': 'Service Date Override', 'verbose_name_plural': 'Service Date Overrides'},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': 'Event Type', 'verbose_name_plural': 'Event Types'},
        ),
        migrations.AddField(
            model_name='eventtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_types/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='end_time',
            field=models.TimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='booking.event', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='start_time',
            field=models.TimeField(verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Weekday'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_email',
            field=models.EmailField(max_length=254, verbose_name='Client email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='Client name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Client phone'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google event ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(related_name='bookings', to='booking.event', verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(db_index=True, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe payment ID'),
        ),
        migrations.AlterField(
            model_name='companyavailability',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='booking.companyprofile', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='companyavailability',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='companyavailability',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='companydateoverride',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='booking.companyprofile', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='companydateoverride',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='companydateoverride',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='companydateoverride',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Is available'),
        ),
        migrations.AlterField(
            model_name='companydateoverride',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='brand_color',
            field=models.CharField(default='#ee5837', max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color or OKLCH format (e.g., oklch(0.68 0.28 296))', regex='^(#[0-9a-fA-F]{6}|oklch\\([\\d.]+%? [\\d.]+ [\\d.]+\\))$')], verbose_name='Brand color'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='currency',
            field=models.CharField(default='EUR', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(default='Con Hilo Depilo', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='companyweekdayslot',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weekday_slots', to='booking.companyprofile', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='companyweekdayslot',
            name='end_time',
            field=models.TimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='companyweekdayslot',
            name='start_time',
            field=models.TimeField(verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='companyweekdayslot',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Weekday'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration_minutes',
            field=models.PositiveIntegerField(verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='booking.eventtype', verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='eventavailability',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='eventavailability',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='booking.event', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='eventavailability',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='eventdateoverride',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='eventdateoverride',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='eventdateoverride',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='booking.event', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='eventdateoverride',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Is available'),
        ),
        migrations.AlterField(
            model_name='eventdateoverride',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='allow_overlap',
            field=models.BooleanField(default=False, verbose_name='Allow overlap'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='payment_model',
            field=models.CharField(choices=[('PRE-PAID', 'Pre-paid'), ('POST-PAID', 'Post-paid')], default='POST-PAID', max_length=20, verbose_name='Payment model'),
        ),
    ]
