# Generated by Django 5.2.13 on 2026-04-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_availabilityslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='availability_free_label',
            field=models.CharField(default='Available', max_length=50, verbose_name='Availability free label'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='availability_no_free_label',
            field=models.CharField(default='Fully Booked', max_length=50, verbose_name='Availability no free label'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='availability_regular_label',
            field=models.CharField(default='Partial', max_length=50, verbose_name='Availability regular label'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='event_label',
            field=models.CharField(default='Consultation', max_length=50, verbose_name='Event label'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='event_type_label',
            field=models.CharField(default='Service Category', max_length=50, verbose_name='Event type label'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='extras_label',
            field=models.CharField(default='Add-ons', max_length=50, verbose_name='Extras label'),
        ),
    ]
